CREATE TABLE COMPONENT_METADATA (
        "COMP_ID" VARCHAR(40) NOT NULL, 
        "SHORTDESC" VARCHAR(100), 
        "DESCRIPTION" VARCHAR(255), 
        "AUTHOR" VARCHAR(100), 
        "VERSION" VARCHAR(100), 
        "DATE_CREATED" DATE, 
        "DATE_MODIFIED" DATE, 
        "LANGUAGE" VARCHAR(25), 
        "SIGNATURE" VARCHAR(255)
        );
 
CREATE TABLE COMPONENT_CODE (
        "COMP_ID" VARCHAR(50) NOT NULL, 
        "CODE" CLOB       
        );
 
CREATE TABLE COMPONENT_ATTRIBUTES (
        "ATTR_ID" VARCHAR(150) NOT NULL,
        "ATTR_DESC" VARCHAR(255),
	"ATTR_TYPE" VARCHAR(100)
        );

INSERT INTO COMPONENT_ATTRIBUTES VALUES ('comp_id',  'Components ID','varchar(40)');
INSERT INTO COMPONENT_ATTRIBUTES VALUES ('shortdesc','Short Description','varchar(100)');
INSERT INTO COMPONENT_ATTRIBUTES VALUES ('description','Two line description','varchar(255)');
INSERT INTO COMPONENT_ATTRIBUTES VALUES ('author','creator of the component','varchar(100)');
INSERT INTO COMPONENT_ATTRIBUTES VALUES ('version','version of the component','varchar(100)');
INSERT INTO COMPONENT_ATTRIBUTES VALUES ('date_created','date of creation','date');
INSERT INTO COMPONENT_ATTRIBUTES VALUES ('date_modified','date of modification','date');
INSERT INTO COMPONENT_ATTRIBUTES VALUES ('language','component code language','varchar(25)');
INSERT INTO COMPONENT_ATTRIBUTES VALUES ('signature','component xml signature','varchar(255)');


ALTER TABLE COMPONENT_METADATA 
    ADD CONSTRAINT "METADATA_PK_CONS" PRIMARY KEY ("COMP_ID");

ALTER TABLE COMPONENT_CODE 
    ADD CONSTRAINT "REQUEST_FK_CONS" FOREIGN KEY ("COMP_ID") REFERENCES COMPONENT_METADATA("COMP_ID");

ALTER TABLE COMPONENT_ATTRIBUTES
    ADD CONSTRAINT "ATTRIBUTES_PK_CONS" PRIMARY KEY ("ATTR_ID");
