
// ----------------------------------------------------------------------
// This code is developed as part of the Java CoG Kit project
// The terms of the license can be found at http://www.cogkit.org/license
// This message may not be removed or altered.
// ----------------------------------------------------------------------

    
package org.globus.cog.gui.grapheditor.targets.swing.util;

import java.awt.AWTEvent;
import java.awt.Component;
/**
 * Class that describes events generated by graph component wrappers
 */
public class GraphComponentWrapperEvent extends AWTEvent{
    public static int UNDEFINED = 0;
    public static int TIP_MOVED = 1;
    public static int TAIL_MOVED = 2;
    public static int MOVED = 3;
    public static int RESIZED = 4;
    public static int REQUEST_SELECTION = 5;
    public static int REQUEST_UNSELECTION = 6;

    private int type;
    
    public GraphComponentWrapperEvent(Component source, int type){
        super(source, -1);
        this.type = type;
    }
    
    public void setType(int type){
        this.type = type;
    }
    
    public int getType(){
        return type;
    }
    
    public GraphComponentWrapper getWrapper() {
    	return (GraphComponentWrapper) getSource();
    }
}
