#! /bin/sh

EXEC=org.apache.derby.tools.ij
DATABASELOCATION=c:/sc2005
OPTIONS="-D'ij.database=workflowRepository;create=true'"


CYGWIN=
CPDELIM=":"

if echo `uname` | grep -i "cygwin"; then
    CYGWIN="yes"
    CPDELIM=";"
fi

updateOptions() {

    if [ "X$1" != "X" ] ; then
        OPTIONS="$OPTIONS -D$2=$1"
    fi

}


####### MAIN BODY ##########

if [ ! -d "$COG_INSTALL_PATH" ] ; then
    COG_INSTALL_PATH=`dirname $0`"/.."
    if [ ! -f "$COG_INSTALL_PATH/lib/derby.jar" ] && [ ! -f  "$COG_INSTALL_PATH/lib/derbytools.jar" ] ; then
                MY_PATH=`which $0`
                COG_INSTALL_PATH=`dirname $MY_PATH`"/.."
                if [ ! -f "$COG_INSTALL_PATH/lib/derby.jar" ] && [ ! -f  "$COG_INSTALL_PATH/lib/derbytools.jar" ] ; then
                echo "Error: COG_INSTALL_PATH is not set, and all attempts at guessing it failed"
                exit
                fi
    fi
fi

LOCALCLASSPATH=$CLASSPATH$CPDELIM$COG_INSTALL_PATH/etc
for JAR in $COG_INSTALL_PATH/lib/*.jar; do
        LOCALCLASSPATH="$LOCALCLASSPATH$CPDELIM$JAR"
done

CMDLINE=$COG_INSTALL_PATH/etc/repository_schema_derby.sql

updateOptions "true" "derby.infolog.append"
updateOptions "jdbc:derby:directory:$DATABASELOCATION/database/" "ij.protocol"
#updateOptions "'workflowRepository:create=true'" "ij.database"


### EXECUTE IJ TO CREATE A DATABASE############
echo ==============================================
    echo java ${OPTIONS} ${COG_OPTS} -classpath ${LOCALCLASSPATH} ${EXEC} ${CMDLINE}
echo ==============================================

if test -n "$CYGWIN"; then
    set CLASSPATHSAVE=$CLASSPATH
    export CLASSPATH="$LOCALCLASSPATH"
    #echo $CLASSPATH
    echo java ${OPTIONS} ${COG_OPTS} ${EXEC} ${CMDLINE}
    eval java ${OPTIONS} ${COG_OPTS} ${EXEC} ${CMDLINE}
    export CLASSPATH=$CLASSPATHSAVE
else
    eval java ${OPTIONS} ${COG_OPTS} -classpath ${LOCALCLASSPATH} ${EXEC} ${CMDLINE}
fi
return_code=$?

### LOAD COMPONENTS INTO THE REPOSITORY USING KARAJAN ####

#eval ./cog-workflow ../examples/repository/createRepository.xml

exit $return_code
