#!/bin/bash

# run this with vdlc on the path, with pwd set to the directory
# in which you found this script, so that it can find the working/ etc
# subdirectories.

pushd working
#rm -v *.?ml
for a in *.dtm; do 
  echo Attempting vdlc known-good $a
  b=$(basename -s .dtm $a).xml
  if [ ! -f $b ] ; then 
    vdlc $a
  else
    touch /tmp/ads
  fi
  VDLCRETURN=$?
  if [ "$VDLCRETURN" -ne "0" ]; then 
    echo "COMPILE FAILED WITH RETURN CODE $VDLCRETURN"
    exit 1
  fi
  diff -q $b ../working-base/$b
  if [ "$?" -ne "0" ]; then
    echo "OUTPUT DIFFERS"
    diff -U 100000 ../working-base/$b $b
    exit 1
  fi
  echo ----------===========================----------
done
popd

pushd not-working
rm -v *.?ml
for a in *.dtm; do

  echo Attempting vdlc known-bad $a
  vdlc $a
  if [ "$?" -eq "0" ]; then echo "TEST FAILED - COMPILE SUCCEEDED"; exit; fi
  echo ----------===========================----------
done
echo Finished all syntax tests
exit 0

