#! /bin/sh 

EXEC=@class@
OPTIONS=

CYGWIN=
CPDELIM=":"
HEAPMAX=

@umask@

if echo `uname` | grep -i "cygwin"; then
    CYGWIN="yes"
    CPDELIM=";"
fi

fixCommandLine() {

    COMMANDLINE=

    while [ "X$1" !=  "X" ] ; do
        COMMANDLINE="${COMMANDLINE} '$1'"
        shift
    done

    echo $COMMANDLINE
}

updateOptions() {
 
    if [ "X$1" != "X" ] ; then
	OPTIONS="$OPTIONS -D$2=$1"
    fi

}

####### MAIN BODY ##########

if [ ! -d "$COG_INSTALL_PATH" ] ; then
    COG_INSTALL_PATH=`dirname $0`"/.."
    if [ ! -f "$COG_INSTALL_PATH/lib/@jar@" ] && [ ! -f "$COG_INSTALL_PATH/lib/cog.jar" ] ; then
		MY_PATH=`which $0`
		COG_INSTALL_PATH=`dirname $MY_PATH`"/.."
		if [ ! -f "$COG_INSTALL_PATH/lib/@jar@" ] && [ ! -f "$COG_INSTALL_PATH/lib/cog.jar" ] ; then
	    	echo "Error: COG_INSTALL_PATH is not set, and all attempts at guessing it failed"
	    	exit
		fi
    fi
fi

OPTIONS="$OPTIONS -Djava.endorsed.dirs=$COG_INSTALL_PATH/lib/endorsed"

LOCALCLASSPATH=$COG_INSTALL_PATH/etc
for JAR in $COG_INSTALL_PATH/lib/*.jar; do
	LOCALCLASSPATH="$LOCALCLASSPATH$CPDELIM$JAR"
done
LOCALCLASSPATH=$LOCALCLASSPATH$CPDELIM$CLASSPATH

CMDLINE=`fixCommandLine "$@"`

### SETUP OTHER ENV VARIABLES ####

USERID=`id | awk '{printf("%s\n", substr($1, 5, index($1, "(")-5 ) ) }'`

if [ "X$GLOBUS_HOSTNAME" = "X" ] && [ "X$HOSTNAME" != "X" ]; then 
	GLOBUS_HOSTNAME=$HOSTNAME  
fi

updateOptions "$USERID" "UID"
updateOptions "$GLOBUS_INSTALL_PATH" "GLOBUS_INSTALL_PATH"
updateOptions "$GLOBUS_DEPLOY_PATH" "GLOBUS_DEPLOY_PATH"
updateOptions "$GLOBUS_TCP_PORT_RANGE" "GLOBUS_TCP_PORT_RANGE"
updateOptions "$GLOBUS_TCP_SOURCE_PORT_RANGE" "GLOBUS_TCP_SOURCE_PORT_RANGE"
updateOptions "$GLOBUS_UDP_SOURCE_PORT_RANGE" "GLOBUS_UDP_SOURCE_PORT_RANGE"
updateOptions "$GLOBUS_HOSTNAME" "GLOBUS_HOSTNAME"
updateOptions "$X509_USER_CERT" "X509_USER_CERT"
updateOptions "$X509_USER_KEY" "X509_USER_KEY"
updateOptions "$X509_CERT_DIR" "X509_CERT_DIR"
updateOptions "$X509_USER_PROXY" "X509_USER_PROXY"
updateOptions "$COG_INSTALL_PATH" "COG_INSTALL_PATH"

if [ "X$HEAPMAX" != "X" ]; then
	OPTIONS="-Xmx$HEAPMAX $OPTIONS"
fi

### EXECUTE ############
if test -n "$CYGWIN"; then
    set CLASSPATHSAVE=$CLASSPATH
    export CLASSPATH="$LOCALCLASSPATH"
    eval java ${OPTIONS} ${COG_OPTS} ${EXEC} ${CMDLINE}
    export CLASSPATH=$CLASSPATHSAVE
else
    eval java ${OPTIONS} ${COG_OPTS} -classpath ${LOCALCLASSPATH} ${EXEC} ${CMDLINE}
fi
return_code=$?

exit $return_code


