#!/bin/bash

TARGETS="execute.event execute2.event execute.global.event"


LOG=$(pwd)/../logs/first-r2522.log

rm  -f $TARGETS
for t in $TARGETS ; do
  swift-plot-log $LOG $t

  l=$(basename $LOG .log)


  diff -q $t $t.$l.expected

  if [ "$?" -ne "0" ]; then
    echo "OUTPUT DIFFERS for log $l in target $t"
    diff -u $t $t.$l.expected
    exit 1
  fi
done


