<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="ManagedJobFactory" targetNamespace="http://www.globus.org/namespaces/2004/10/gram/job/bindings" xmlns:porttype="http://www.globus.org/namespaces/2004/10/gram/job" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import namespace="http://www.globus.org/namespaces/2004/10/gram/job" location="managed_job_factory_port_type.wsdl"/>
  <wsdl:binding name="ManagedJobFactoryPortTypeSOAPBinding" type="porttype:ManagedJobFactoryPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="createManagedJob">
      <soap:operation soapAction="http://www.globus.org/namespaces/2004/10/gram/job/ManagedJobFactoryPortType/createManagedJobRequest"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="createManagedJobFault">
        <soap:fault name="createManagedJobFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="QueryResourceProperties">
      <soap:operation soapAction="http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceProperties/QueryResourceProperties"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="InvalidResourcePropertyQNameFault">
        <soap:fault name="InvalidResourcePropertyQNameFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="InvalidQueryExpressionFault">
        <soap:fault name="InvalidQueryExpressionFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="QueryEvaluationErrorFault">
        <soap:fault name="QueryEvaluationErrorFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="ResourceUnknownFault">
        <soap:fault name="ResourceUnknownFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="UnknownQueryExpressionDialectFault">
        <soap:fault name="UnknownQueryExpressionDialectFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="GetMultipleResourceProperties">
      <soap:operation soapAction="http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceProperties/GetMultipleResourceProperties"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="InvalidResourcePropertyQNameFault">
        <soap:fault name="InvalidResourcePropertyQNameFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="ResourceUnknownFault">
        <soap:fault name="ResourceUnknownFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="GetResourceProperty">
      <soap:operation soapAction="http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceProperties/GetResourceProperty"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="InvalidResourcePropertyQNameFault">
        <soap:fault name="InvalidResourcePropertyQNameFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="ResourceUnknownFault">
        <soap:fault name="ResourceUnknownFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>
