<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="ManagedJobFactory" targetNamespace="http://www.globus.org/namespaces/2004/10/gram/job/service" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:binding="http://www.globus.org/namespaces/2004/10/gram/job/bindings" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import namespace="http://www.globus.org/namespaces/2004/10/gram/job/bindings" location="managed_job_factory_bindings.wsdl"/>
  <wsdl:service name="ManagedJobFactoryService">
    <wsdl:port name="ManagedJobFactoryPortTypePort" binding="binding:ManagedJobFactoryPortTypeSOAPBinding">
      <soap:address location="http://localhost:8080/wsrf/services/"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
