#!/bin/bash


echo Removing files from previous runs
rm -fv *.out *.xml *.kml *.dot *.log *.rlog


if [ "X$1" == "X" ]; then
  TESTS=*.swift
else
  TESTS="$@"
fi

for testfn in $TESTS; do

  export t=$(basename $testfn .swift)
  export EXPECTEDS="$t.*.expected"

  echo Running test $t
  swift ${t}.swift

  if [ "$?" -ne "0" ]; then echo "SWIFT RETURN CODE NON-ZERO"; exit 1; fi

  echo expecting $EXPECTEDS

  for e in $EXPECTEDS; do

    if [ -f $e ]; then

      echo checking $e
      out=$(basename $e .expected)

      diff -q ${out} ${e}
      if [ "$?" -ne "0" ]; then echo "OUTPUT DIFFERS"; exit 1; fi

    else
      echo "$e does not exist"
    fi

  done
  echo ----------===========================----------
done

echo All language behaviour tests passed

exit 0

