#!/bin/bash

# get execute2 events. sort them so that they're grouped by
# job and then ordered by time

make LOG=$1 clean execute2.last

cat execute2.last | sed 's/^\([^ ]*\) \([^ ]*\) \([^ ]*\)\(.*\)/\1 \3 \4/'

