#!/bin/sh

/bin/pwd 1>&2

rm -f tmp-extract-starttime2

if [[ $LOG == "" ]] ; then 
  LOG=$1
fi

if [ "X$LOG" != "X" ] ; then
  head $LOG | iso-to-secs >> tmp-extract-starttime2
else 
  echo "No LOG given!"
  exit 1
fi

# for e in *.event ; do
#   head -n 1 $e >> tmp-extract-starttime2
# done

sort -n < tmp-extract-starttime2 >tmp-extract-starttime

read st rest < tmp-extract-starttime

echo $st
