#!/bin/bash

#2007-09-23 15:02:04,726+0100 INFO  vdl:execute2 Running job badmonkey-7glgsmhi badmonkey with arguments [in.txt, out.0001.txt] in badmonkey-20070923-1501-i5sjvxk1/badmonkey-7glgsmhi on UC

#2007-09-26 16:10:51,917 DEBUG vdl:execute2 Job antch-l41y7shi running in thread 0-1-2-0 run 20070926-1559-gpuago4f

grep "vdl:execute2 Job $1 running in thread " log  | sed 's/^.* running in thread \([0-9\-]*\) .*$/\1/'
