#!/bin/bash

# this will take a log file and produce a set of state transition
# events for every karajan task entity 

# grep filters down to mostly relevant lines first - this is quick
# reduces the more expensive later processing

# then convert timestamps

# then change relevant lines to transition format

# then filter out unchanged lines because they're irrelevant

grep ' TaskImpl ' | iso-to-secs | \
sed 's/^\([^ ]*\) [^ ]* TaskImpl Task(type=\([^,]*\), identity=urn:\([^)]*\)) setting status to \([^ ]*\) *\(.*\)$/\1 \3 \4 \2 \5/' | \
sed 's/\([^ ]*\) \([^ ]*\) Unknown \([^ ]*\) *(\(.*\))/\1 \2 Unknown-\4 \3/' 

exit 0

