#!/bin/bash

# this will take a log file and produce a set of state transition
# events for every initshareddir transition

grep ' vdl:initshareddir ' | iso-to-secs | \
grep -E '^[^ ]+ +[^ ]+ +vdl:initshareddir ' | \
sed 's/\([^ ]*\) INFO  vdl:initshareddir START host=\([^ ]*\) -.*$/\1 \2 START/' |\
sed 's/\([^ ]*\) INFO  vdl:initshareddir END host=\([^ ]*\) -.*$/\1 \2 END/' |\
 grep -E '^[^$]'

exit 0
