#!/bin/bash

ST=$(cat start-time.tmp)

I=0

for taskid in $(cat tasks.list); do
  extract-activity-for-task $taskid > tfat.tmp
  sort < tfat.tmp > tfat2.tmp
  START=$(head -n 1 tfat2.tmp | cut -f 1 -d ' ')
  END=$(tail -n 1 tfat2.tmp | cut -f 1 -d ' ')
  DURATION=$(( $END - $START ))
  echo $(( $START - $ST )) $I $DURATION 0 $taskid
  I=$(( $I + 1))
done
