<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="ServiceGroup" targetNamespace="http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ServiceGroup-1.2-draft-01.wsdl/service" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:binding="http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ServiceGroup-1.2-draft-01.wsdl/bindings">
  <wsdl:import namespace="http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ServiceGroup-1.2-draft-01.wsdl/bindings" location="WS-ServiceGroup_bindings.wsdl"/>
  <wsdl:service name="ServiceGroupService">
    <wsdl:port name="ServiceGroupEntryPort" binding="binding:ServiceGroupEntrySOAPBinding">
      <soap:address location="http://localhost:8080/wsrf/services/"/>
    </wsdl:port>
    <wsdl:port name="ServiceGroupPort" binding="binding:ServiceGroupSOAPBinding">
      <soap:address location="http://localhost:8080/wsrf/services/"/>
    </wsdl:port>
    <wsdl:port name="ServiceGroupRegistrationPort" binding="binding:ServiceGroupRegistrationSOAPBinding">
      <soap:address location="http://localhost:8080/wsrf/services/"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
