package org.globus.transfer.reliable.client.credential;

import org.globus.tools.proxy.GridProxyInit;
import org.globus.transfer.reliable.client.credential.myproxy.MyProxyLogonGUI;

public class CredentialDialog extends javax.swing.JDialog {
    
    /** Creates new form CredentialDialog */
    public CredentialDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        generate_proxy = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Myproxy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Credential");

        jLabel1.setText("If you want to generate a proxy certificate on your local \nmachine, please select this");

        generate_proxy.setText("generate");
        generate_proxy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generate_proxyActionPerformed(evt);
            }
        });

        jLabel2.setText("If you want to get a proxy certificate from MyPorxy, please select this");

        Myproxy.setText("Myproxy");
        Myproxy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MyproxyActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 474, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 484, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(generate_proxy)
                    .add(Myproxy))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(generate_proxy))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(Myproxy))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void generate_proxyActionPerformed(java.awt.event.ActionEvent evt) {
        GridProxyInit proxyInitFrame = new GridProxyInit(null, true);
        proxyInitFrame.setRunAsApplication(false);
        proxyInitFrame.setCloseOnSuccess(true);
        proxyInitFrame.setLocation(50, 50);
        proxyInitFrame.pack();
        //UITools.center(mainPanel, proxyInitFrame);
        this.setVisible(false);
        proxyInitFrame.setVisible(true); 
        
    }

    private void MyproxyActionPerformed(java.awt.event.ActionEvent evt) {
        MyProxyLogonGUI.main(null);
        this.setVisible(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CredentialDialog dialog = new CredentialDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify
    private javax.swing.JButton Myproxy;
    private javax.swing.JButton generate_proxy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration
    
}
