<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="NotificationConsumer" targetNamespace="http://wsrf.globus.org/core/notification/bindings" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:porttype="http://wsrf.globus.org/core/notification" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:import namespace="http://wsrf.globus.org/core/notification" location="notification_consumer_flattened.wsdl"/>
  <wsdl:binding name="ConsumerSOAPBinding" type="porttype:Consumer">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="Notify">
      <soap:operation soapAction="http://docs.oasis-open.org/wsn/2004/06/wsn-WS-BaseNotification/Notify"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>
