<?xml version="1.0" encoding="UTF-8"?>
<definitions name="NotificationConsumer" targetNamespace="http://wsrf.globus.org/core/notification" xmlns:tns="http://wsrf.globus.org/core/notification" xmlns:wsdlpp="http://www.globus.org/namespaces/2004/10/WSDLPreprocessor" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/03/addressing" xmlns:wsntw="http://docs.oasis-open.org/wsn/2004/06/wsn-WS-BaseNotification-1.2-draft-01.wsdl" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <import namespace="http://docs.oasis-open.org/wsn/2004/06/wsn-WS-BaseNotification-1.2-draft-01.wsdl" location="../../wsrf/notification/WS-BaseN.wsdl"/>
  <import namespace="http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceLifetime-1.2-draft-01.wsdl" location="../../wsrf/lifetime/WS-ResourceLifetime.wsdl"/>
  <import namespace="http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceProperties-1.2-draft-01.wsdl" location="../../wsrf/properties/WS-ResourceProperties.wsdl"/>
  <types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://wsrf.globus.org/core/notification" xmlns:tns="http://wsrf.globus.org/core/notification" xmlns:wsrp="http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceProperties-1.2-draft-01.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<xsd:import namespace="http://schemas.xmlsoap.org/ws/2004/03/addressing" schemaLocation="../../ws/addressing/WS-Addressing.xsd"/>

     
            <xsd:import namespace="http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceProperties-1.2-draft-01.xsd" schemaLocation="../../wsrf/properties/WS-ResourceProperties.xsd"/>

            <xsd:complexType name="ResourcePropertyValueChangeNotificationElementType">
                <xsd:sequence>
                    <xsd:element maxOccurs="1" minOccurs="1" ref="wsrp:ResourcePropertyValueChangeNotification"/>
                </xsd:sequence>
            </xsd:complexType>
        </xsd:schema>
  </types>
  <portType name="Consumer">
    <operation name="Notify">
      <input message="wsntw:Notify" wsa:Action="http://docs.oasis-open.org/wsn/2004/06/wsn-WS-BaseNotification/Notify"/>
    </operation>
  </portType>
</definitions>
