#!/bin/bash

# generate an integer in a file, where that file is generated by a slow
# executing procedure invocation

# this is intended to test how well extractint works with

# TODO should also make tests for readData and readData2

rm -f *.kml

echo "localhost 	slowint 		$(pwd)/extract-int-delayed-slowint.sh	INSTALLED	INTEL32::LINUX	null" > ./extract-int-delayed-tc.data

swift -tc.file ./extract-int-delayed-tc.data extract-int-delayed.swift
