<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="Shutdown" targetNamespace="http://wsrf.globus.org/core/shutdown/bindings" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:porttype="http://wsrf.globus.org/core/shutdown" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:import namespace="http://wsrf.globus.org/core/shutdown" location="shutdown_port_type.wsdl"/>
  <wsdl:binding name="ShutdownPortTypeSOAPBinding" type="porttype:ShutdownPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="shutdown">
      <soap:operation soapAction="http://wsrf.globus.org/core/shutdown/ShutdownPortType/shutdownRequest"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>
