/*
 * Copyright 2012 University of Chicago
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * Created on Sep 19, 2015
 */
package org.griphyn.vdl.util;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileFilter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;

public class ScriptTemplateProcessor {
    public static void main(String[] args) {
        try {
            run(args[0]);
            System.exit(0);
        }
        catch (Exception e) {
            e.printStackTrace();
            System.exit(1);
        }
    }

    private static void run(String dir) throws Exception {
        File[] fs = new File(dir).listFiles(new FileFilter() {
            @Override
            public boolean accept(File f) {
                return f.getName().endsWith(".in");
            }
        });
        
        for (File f : fs) {
            process(f);
        }
    }

    private static void process(File f) throws Exception {
        String inName = f.getAbsolutePath();
        String outName = inName.substring(0, inName.length() - 3);
        BufferedWriter w = new BufferedWriter(new FileWriter(outName));
        
        if (outName.endsWith(".vbs")) {
            w.write("' ");
        }
        else {
            w.write("# ");
        }
        w.write("Do not edit this file directly since it is automatically generated. Instead, edit the template: " + inName + "\n\n");
        
        write(w, f);
        
        w.close();
    }

    private static void write(BufferedWriter w, File f) throws IOException {
        BufferedReader r = new BufferedReader(new FileReader(f));
        String line = r.readLine();
        while (line != null) {
            if (line.startsWith("#include")) {
                String[] ss = line.split("\\s+", 2);
                write(w, new File(f.getParent(), ss[1]));
            }
            else {
                w.write(line);
                w.write('\n');
            }
            line = r.readLine();
        }
        r.close();
    }
}
