<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="WS-BaseNotification" targetNamespace="http://docs.oasis-open.org/wsn/2004/06/wsn-WS-BaseNotification-1.2-draft-01.wsdl/service" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:binding="http://docs.oasis-open.org/wsn/2004/06/wsn-WS-BaseNotification-1.2-draft-01.wsdl/bindings">
  <wsdl:import namespace="http://docs.oasis-open.org/wsn/2004/06/wsn-WS-BaseNotification-1.2-draft-01.wsdl/bindings" location="WS-BaseN_bindings.wsdl"/>
  <wsdl:service name="WS-BaseNotificationService">
    <wsdl:port name="NotificationConsumerPort" binding="binding:NotificationConsumerSOAPBinding">
      <soap:address location="http://localhost:8080/wsrf/services/"/>
    </wsdl:port>
    <wsdl:port name="NotificationProducerPort" binding="binding:NotificationProducerSOAPBinding">
      <soap:address location="http://localhost:8080/wsrf/services/"/>
    </wsdl:port>
    <wsdl:port name="SubscriptionManagerPort" binding="binding:SubscriptionManagerSOAPBinding">
      <soap:address location="http://localhost:8080/wsrf/services/"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
