#!/bin/bash


rm -f /tmp/stsubmit
EXECUTABLE=
DIR=
ARGS=
STDOUTLOC=
STDOUTPATH=
STDERRLOC=
STDERRPATH=
STDINLOC=
STDINPATH=
STDIN=
STDOUT=
STDERR=

while read LINE; do
	echo $LINE >>/tmp/stsubmit
	case $LINE in
		executable=*)
			EXECUTABLE=${LINE#executable=}
			;;
		directory=*)
			DIR=${LINE#directory=}
			;;
		arg=*)
			ARGS="$ARGS ${LINE#arg=}"
			;;
		attr.*)
			# ignore attributes
			;;
		stdin.location=*)
			STDINLOC=${LINE#stdin.location=}
			;;
		stdin.path=*)
			STDINPATH=${LINE#stdin.path=}
			;;
		stdout.location=*)
			STDOUTLOC=${LINE#stdout.location=}
			;;
		stdout.path=*)
			STDOUTPATH=${LINE#stdout.path=}
			;;
		stderr.location=*)
			STDERRLOC=${LINE#stderr.location=}
			;;
		stderr.path=*)
			STDERRPATH=${LINE#stderr.path=}
			;;
		env.*)
			LINE2=${LINE#env.}
			# split on '='
			ELS=(${LINE2//=/})
			NAME=${ELS[0]}
			VALUE=${ELS[1]}
			export $NAME=$VALUE
			;;
		*)
			echo "Don't know how to interpret line: $LINE" >&2
			exit 2
	esac
done < /dev/stdin

if [ "$STDOUTLOC" == "tmp" ]; then
	STDOUTPATH=$(mktemp)
	echo "stdout.path=$STDOUTPATH"
fi
if [ "$STDOUTPATH" != "" ]; then
	STDOUT="1> $STDOUTPATH"
fi

if [ "$STDERRLOC" == "tmp" ]; then
	STDERRPATH=$(mktemp)
	echo "stderr.path=$STDERRPATH"
fi
if [ "$STDERRPATH" != "" ]; then
	STDERR="2> $STDERRPATH"
fi

if [ "$STDINLOC" != "" ]; then
	STDIN="< $STDINLOC"
fi

CMD="$EXECUTABLE $ARGS $STDIN $STDOUT $STDERR"

cd $DIR
$CMD &

echo "jobid=$!"

exit 0