<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="AuthorizationService" targetNamespace="http://www.gridforum.org/namespaces/2004/03/ogsa-authz/saml/bindings" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:porttype="http://www.gridforum.org/namespaces/2004/03/ogsa-authz/saml" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:import namespace="http://www.gridforum.org/namespaces/2004/03/ogsa-authz/saml" location="authz_port_type.wsdl"/>
  <wsdl:binding name="SAMLRequestPortTypeSOAPBinding" type="porttype:SAMLRequestPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="SAMLRequest">
      <soap:operation soapAction="http://www.gridforum.org/namespaces/2004/03/ogsa-authz/saml/SAMLRequestPortType/SAMLRequestRequest"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetResourceProperty">
      <soap:operation soapAction="http://www.gridforum.org/namespaces/2004/03/ogsa-authz/saml/SAMLRequestPortType/GetResourcePropertyRequest"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="InvalidResourcePropertyQNameFault">
        <soap:fault name="InvalidResourcePropertyQNameFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="ResourceUnknownFault">
        <soap:fault name="ResourceUnknownFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="SetResourceProperties">
      <soap:operation soapAction="http://www.gridforum.org/namespaces/2004/03/ogsa-authz/saml/SAMLRequestPortType/SetResourcePropertiesRequest"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="InvalidResourcePropertyQNameFault">
        <soap:fault name="InvalidResourcePropertyQNameFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="SetResourcePropertyRequestFailedFault">
        <soap:fault name="SetResourcePropertyRequestFailedFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="ResourceUnknownFault">
        <soap:fault name="ResourceUnknownFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="UnableToModifyResourcePropertyFault">
        <soap:fault name="UnableToModifyResourcePropertyFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="InvalidSetResourcePropertiesRequestContentFault">
        <soap:fault name="InvalidSetResourcePropertiesRequestContentFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="QueryResourceProperties">
      <soap:operation soapAction="http://www.gridforum.org/namespaces/2004/03/ogsa-authz/saml/SAMLRequestPortType/QueryResourcePropertiesRequest"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="UnknownQueryExpressionDialectFault">
        <soap:fault name="UnknownQueryExpressionDialectFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="InvalidResourcePropertyQNameFault">
        <soap:fault name="InvalidResourcePropertyQNameFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="ResourceUnknownFault">
        <soap:fault name="ResourceUnknownFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="InvalidQueryExpressionFault">
        <soap:fault name="InvalidQueryExpressionFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="QueryEvaluationErrorFault">
        <soap:fault name="QueryEvaluationErrorFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>
