#!/bin/bash

# 2007-09-23 14:05:36,996+0100 INFO  vdl:execute goodmonkey completed in thread 0-3 uid $u3p4qmhi
# 2007-09-23 14:08:07,042+0100 INFO  vdl:execute badmonkey failed in thread 0-2 uid $x3p4qmhi

cat log | grep "INFO  vdl:execute " | grep "completed in thread" > elt.tmp
cat log | grep "INFO  vdl:execute " | grep "failed in thread" >> elt.tmp
grep -E "thread $1\$" elt.tmp | sed 's/^\(.*\) INFO  vdl:execute \([^ ]*\) \([^ ]*\) in thread [0-9\-]*.*$/\1/'

# this regexp puts time in \1, app name in \2, thread id in \3 and
# invocation id in \4  (which should match $1 parameter to script)

