#!/bin/bash

# give the path to info directory as parameter

for infofn in $1/*-info; do
  jobid=$(echo $infofn | sed 's%^.*/\([^/]*\)-info$%\1%' )
  echo job $jobid >&2
  STARTTIME=$(grep -E '^Progress ' $infofn | sed "s/^Progress *\([^ ]* [^ ]*\) *\([^ ]*\).*/\1 $jobid \2/" | head -n 1 | iso-to-secs | cut -d ' ' -f 1)
  OFFSET=$(echo $STARTTIME - $(cat start-time.tmp) | bc -l)
# Progress  2007-10-29 10:05:50+0000  RM_JOBDIR
  grep -E '^Progress ' $infofn | sed "s/^Progress *\([^ ]* [^ ]*\) *\([^ ]*\).*/\1 $jobid \2/" | iso-to-secs | normalise-event-start-time-to-any $OFFSET
done | swap-and-sort-and-swap
