#!/bin/bash

#usage: ./minmem path/to/oom.log

if [ $# -ne 1  ]
then
echo "usage: $0 /path/to/oom.log"
fi

minmem=4000
for mem in `cat $1 | cut -d" " -f 10`
do
 if [ $mem -le $minmem ]
 then
  minmem=$mem
 fi
done
echo $minmem
