#! /bin/sh

set -x
export GLOBUS_HOSTNAME="128.135.112.73"
export GLOBUS_TCP_PORT_RANGE=50000,51000

swift -config swift.properties -sites.file sites.template.xml -tc.file tc.template.data modis.swift -modisdir=input/
