import(sys)

namespace(xs) {
	export(schema, def("org.griphyn.vdl.karajan.lib.XS$Schema"))
	export(simpleType, def("org.griphyn.vdl.karajan.lib.XS$SimpleType"))
	export(restriction, def("org.griphyn.vdl.karajan.lib.XS$Restriction"))
	export(complexType, def("org.griphyn.vdl.karajan.lib.XS$ComplexType"))
	export(sequence, def("org.griphyn.vdl.karajan.lib.XS$Sequence"))
	export(element, def("org.griphyn.vdl.karajan.lib.XS$Element"))
}
