#!/bin/bash


rm -f /tmp/stsubmit
EXECUTABLE=
DIR=
ARGS=
STDOUTLOC=
STDOUTPATH=
STDERRLOC=
STDERRPATH=
STDINLOC=
STDINPATH=
STDIN=
STDOUT=
STDERR=

while read LINE; do
	echo $LINE >>/tmp/stsubmit
	case $LINE in
		executable=*)
			EXECUTABLE=${LINE#executable=}
			;;
		directory=*)
			DIR=${LINE#directory=}
			;;
		arg=*)
            if [[ ${LINE#arg=} == *cscript*pl ]]
            then
                # We are replacing with a specific temporary worker script
                ARGS="$ARGS /usr/local/bin/swift-trunk/bin/worker.pl"
            else
                ARGS="$ARGS ${LINE#arg=}"
            fi
			;;
		attr.*)
			# ignore attributes
			;;
		stdin.location=*)
			STDINLOC=${LINE#stdin.location=}
			;;
		stdin.path=*)
			STDINPATH=${LINE#stdin.path=}
			;;
		stdout.location=*)
			STDOUTLOC=${LINE#stdout.location=}
			;;
		stdout.path=*)
			STDOUTPATH=${LINE#stdout.path=}
			;;
		stderr.location=*)
			STDERRLOC=${LINE#stderr.location=}
			;;
		stderr.path=*)
			STDERRPATH=${LINE#stderr.path=}
			;;
		env.*)
			LINE2=${LINE#env.}
			# split on '='
			ELS=(${LINE2//=/})
			NAME=${ELS[0]}
			VALUE=${ELS[1]}
			export $NAME=$VALUE
			;;
		*)
			echo "Don't know how to interpret line: $LINE" >&2
			exit 2
	esac
done < /dev/stdin

if [ "$STDOUTLOC" == "tmp" ]; then
	STDOUTPATH=$(mktemp)
	echo "stdout.path=$STDOUTPATH"
fi
if [ "$STDOUTPATH" != "" ]; then
	STDOUT="1> $STDOUTPATH"
fi

if [ "$STDERRLOC" == "tmp" ]; then
	STDERRPATH=$(mktemp)
	echo "stderr.path=$STDERRPATH"
fi
if [ "$STDERRPATH" != "" ]; then
	STDERR="2> $STDERRPATH"
fi

if [ "$STDINLOC" != "" ]; then
	STDIN="< $STDINLOC"
fi

LOG=/home/yadu/src/swift-trunk/cog/modules/provider-localscheduler/examples/ec2-cloud-provider/log
echo "Start" > $LOG
CMD="$EXECUTABLE $ARGS $STDIN $STDOUT $STDERR"
echo "CMD     : $CMD" >> $LOG

#SUBMIT_SCRIPT=$(mktemp)
SUBMIT_SCRIPT=/tmp/submit_script_$RANDOM

# TODO : Cleanup
cat /home/yadu/src/swift-trunk/cog/modules/provider-localscheduler/examples/ec2-cloud-provider/configs > $SUBMIT_SCRIPT
DIR=/tmp/
# TODO : Fix me

cat<<EOF >> $SUBMIT_SCRIPT
CMD_STRING="mkdir $DIR; cd $DIR; $CMD"
EOF

cat $SUBMIT_SCRIPT >> $LOG

echo "$PWD" >> $LOG
echo "python /home/yadu/src/swift-trunk/cog/modules/provider-localscheduler/examples/ec2-cloud-provider/cloud.py --submit $SUBMIT_SCRIPT" >> $LOG
python /home/yadu/src/swift-trunk/cog/modules/provider-localscheduler/examples/ec2-cloud-provider/cloud.py --submit $SUBMIT_SCRIPT  | tee -a $LOG

echo "ENV" >> $LOG
env >> $LOG
exit 0
