<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="ManagedExecutableJob" targetNamespace="http://www.globus.org/namespaces/2004/10/gram/job/exec/service" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:binding="http://www.globus.org/namespaces/2004/10/gram/job/exec/bindings" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import namespace="http://www.globus.org/namespaces/2004/10/gram/job/exec/bindings" location="managed_executable_job_bindings.wsdl"/>
  <wsdl:service name="ManagedExecutableJobService">
    <wsdl:port name="ManagedExecutableJobPortTypePort" binding="binding:ManagedExecutableJobPortTypeSOAPBinding">
      <soap:address location="http://localhost:8080/wsrf/services/"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
