<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="WS-ResourceProperties" targetNamespace="http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceProperties-1.2-draft-01.wsdl/service" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:binding="http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceProperties-1.2-draft-01.wsdl/bindings">
  <wsdl:import namespace="http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceProperties-1.2-draft-01.wsdl/bindings" location="WS-ResourceProperties_bindings.wsdl"/>
  <wsdl:service name="WS-ResourcePropertiesService">
    <wsdl:port name="QueryResourcePropertiesPort" binding="binding:QueryResourcePropertiesSOAPBinding">
      <soap:address location="http://localhost:8080/wsrf/services/"/>
    </wsdl:port>
    <wsdl:port name="GetMultipleResourcePropertiesPort" binding="binding:GetMultipleResourcePropertiesSOAPBinding">
      <soap:address location="http://localhost:8080/wsrf/services/"/>
    </wsdl:port>
    <wsdl:port name="SetResourcePropertiesPort" binding="binding:SetResourcePropertiesSOAPBinding">
      <soap:address location="http://localhost:8080/wsrf/services/"/>
    </wsdl:port>
    <wsdl:port name="GetResourcePropertyPort" binding="binding:GetResourcePropertySOAPBinding">
      <soap:address location="http://localhost:8080/wsrf/services/"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
