#! /bin/sh 

OPTIONS=

CYGWIN=
CPDELIM=":"
PWD=`pwd`

if echo `uname` | grep -i "cygwin"; then
    CYGWIN="yes"
    CPDELIM=";"
fi

fixCommandLine() {

    COMMANDLINE=

    while [ "X$1" !=  "X" ] ; do
        COMMANDLINE="${COMMANDLINE} \"$1\""
        shift
    done

    echo $COMMANDLINE
}

updateOptions() {
 
    if [ "X$1" != "X" ] ; then
	OPTIONS="$OPTIONS -D$2=$1"
    fi

}

####### MAIN BODY ##########


LOCALCLASSPATH=$CLASSPATH$CPDELIM$PWD/../etc
for JAR in $PWD/../lib/*.jar; do
	LOCALCLASSPATH="$LOCALCLASSPATH$CPDELIM$JAR"
done

CMDLINE=`fixCommandLine "$@"`

### SETUP OTHER ENV VARIABLES ####

USERID=`id | awk '{printf("%s\n", substr($1, 5, index($1, "(")-5 ) ) }'`

updateOptions "$USERID" "UID"
updateOptions "$GLOBUS_INSTALL_PATH" "GLOBUS_INSTALL_PATH"
updateOptions "$GLOBUS_DEPLOY_PATH" "GLOBUS_DEPLOY_PATH"


### EXECUTE ############
if test -n $CYGWIN; then
    export CLASSPATH="$LOCALCLASSPATH:$CLASSPATH"
else
	export CLASSPATH=$LOCALCLASSPATH:$CLASSPATH
fi

