FILE=image-gallery

convert: clean
	@echo --------------------------------------------------
	@echo Create scaled icons
	@echo --------------------------------------------------
	./bin/convert.pl
	@echo --------------------------------------------------

clean:
	rm -f */*-bw.png

distclean: clean
	echo done


