#!/bin/bash

source "$SWIFT_HOME/libexec/aimes-emanager-provider/aimes-swift-config.sh"

SESSION_ID=$(cat $RUNDIR/session_id)
JOBID=$1
CONF=/tmp/$JOBID
EXITCODE=0

log "Received cancel directive for $JOBID"

if ! test -z "$JOBID"
then
    log "Cancelling $JOBID " $(date +"%T")
    (python $AIMES_CLIENT -e $ENDPOINT -z $SESSION_ID -l $RUNDIR/aimes_client.log --cancel $JOBID)
    EXITCODE=$?
    if [[ "$EXITCODE" == "0" ]]
    then
        log "Done cancelling $JOBID" $(date +"%T")
        rm -f $CONF
    else
        log "Failed to cancel $JOBID: returned exitcode:$EXITCODE" $(date +"%T")
    fi

    # we also cancel the session at this point
    # log "Cancelling $SESSION_ID " $(date +"%T")
    # python $AIMES_CLIENT -e $ENDPOINT -z $SESSION_ID -l $RUNDIR/aimes_client.log --destroy_session 
fi

exit $EXITCODE

