#!/bin/bash -x

source "$SWIFT_HOME/libexec/aimes-emanager-provider/aimes-swift-config.sh"

SESSION_ID=$(cat $RUNDIR/session_id)

for JOBID in ${*}
do
    log "Stat'ing for $JOBID"
    (python $AIMES_CLIENT --logfile $LOG --status $JOBID --session $SESSION_ID --endpoint $ENDPOINT | tee -a $LOG)
done

