#!/usr/bin/perl -w
# 2007-09-20 16:13:40,150

use Time::Local;

while (<STDIN>) {
  $n = $_;
# 2007-09-22 01:05:03,263+0100
# 2007-09-21T19:08:35.064-05:00

  if($n =~ /^(....)-(..)-(..)[ T](..):(..):(..)(|[\.,][0-9%N]*)(|[\+-][0123456789][0123456789]:?00)($| .*$)/) {
    $t=timegm($6, $5, $4, $3, $2 - 1, $1);
    $tz=$8;
    $rest=$9;
    $frac=$7;
    if($tz =~ /([\+-][0123456789][0123456789]):?00/) {
      $diff = $1 * 60 * 60;
      $t = $t - $diff;
    }
    $t = $t;
    if ($frac eq "" or $frac eq ".N" or $frac eq ",N" or $frac eq ",%N" or $frac eq ".%N" ) {
      print "$t";
    } else {
      $frac =~ s/[\.,]// ;
      print "$t.$frac";
    }
    print $rest;
    print "\n";
  }
}
